### PR TITLE
Improvement/auth

### PR DESCRIPTION
**Pull request by Mayhem93**
Added support for authentication (the API rate limit is higher when you're logged in)
* Upon reaching the rate limit the request will be retried after the rate limit has been reset according to the http header that github sends

### CODE REVIEW

**Comment by elquimista** [comment]
@Mayhem93 thanks for the PR. I'll review it shortly. Have you ever reached API rate limit by the way?

**Comment by Mayhem93** [comment]
@artificis Yeah, I did even though you're not using the official API. Looks like the link it's being accessed (which just returns a svg) abides to the rules of their API (v3 at least):
* 10 requests per minute for unauthenticated requests
* 5000 per hour for authenticated requests

Feel free to improve it. 

PS: you might want to check the error message instead of just the status code, as 403 can be triggered by other reasons as well (repository banned because of DMCA takedown or the repository being unavailable because of other reasons; I've been through this).

LE: Actually, I think this only happens for the **actual** API reuqest, not sure if it does for the non-api one.

**Comment by elquimista** [comment]
Not sure what repository you're talking about. We're just pulling user's contributation stats data, not individual repository data. What are you using this package for specifically?

**Comment by Mayhem93** [comment]
Oh, I mixed them up 😅. Nevermind  that part then. The rate limit part still stands tho

**Pull request closed without merging**
